CREATE DATABASE catalog_of_my_things;

CREATE TABLE labels (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  color VARCHAR(100) NOT NULL
);

CREATE TABLE books(
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  publish_date DATE NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  cover_state VARCHAR(50) NOT NULL,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  label_id INT NOT NULL REFERENCES labels (id),
);
